Add infix operators for mapOk/flatMapOk
RationalJS/future pull request #27
Opened 2018-11-24 08:07 UTC by johnhaley81

I wanted to see at least what the interest would be in adding some infix operators to the codebase. I chose what I would think are the 2 most common methods to add them to and I lifted the operators from Haskell.

2018-11-26 02:44 UTC, gilbert commented
I don't have any strong opinions. Any thoughts @scull7 @ostera?

2018-11-26 09:21 UTC, scull7 requested changes

2018-11-26 09:21 UTC, scull7 commented on tests/TestFuture.re
> +    (Belt.Result.Ok("two") |. Future.value <$> (s => s ++ "!"))
If we're going to provide the infix operators they should come with their own test and not replace the standard tests.  Tests are documentation, and having the infix operators in their own place would induce much less confusion.

2018-11-26 09:21 UTC, scull7 commented on tests/TestFuture.re
> +      >>= (s => Belt.Result.Ok(s ++ "!") |. Future.value)
I'm not sure this add clarity to the code here. (Also, same admonishment as above.)  Perhaps there's a more clear example which shows the ergonomic gains of the infix operators.

2018-11-26 18:05 UTC, johnhaley81 commented
This might be out of scope, but running `npm run test:only` returns an error locally and it looks like it's also [doing the same in CI](https://travis-ci.org/RationalJS/future/jobs/459866018#L1515).

This is without my changes.

2018-11-26 18:21 UTC, scull7 commented
@johnhaley81 I've opened an issue so the CI failure can be addressed separately

2018-11-26 18:25 UTC, scull7 commented on tests/TestFuture.re
> +      |. equals("infix ops rock!2")
Where does the `2` come from?

2018-11-26 18:32 UTC, johnhaley81 commented on tests/TestFuture.re
> +      |. equals("infix ops rock!2")
🤦‍♂️ from me leaving that in to see if the test would fail (it didn't) when I was researching #29.

I'll change that.

2018-11-27 05:01 UTC, johnhaley81 commented
@scull7 are these changes sufficient or am I missing something?

2018-11-27 05:27 UTC, scull7 approved these changes

2018-11-27 05:28 UTC, scull7 commented
Sorry it took me so long to get back to this.

2018-11-27 13:32 UTC, johnhaley81 commented
No worries. Thanks!

2018-11-29 17:42 UTC, gilbert commented
Thanks all!

2018-11-29 17:42 UTC, merged